package uibk.llmape.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BattleAsserts {

	/**
	 * Asserts that the entity has all properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertBattleAllPropertiesEquals(Battle expected, Battle actual) {
		assertBattleAutoGeneratedPropertiesEquals(expected, actual);
		assertBattleAllUpdatablePropertiesEquals(expected, actual);
	}

	/**
	 * Asserts that the entity has all updatable properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertBattleAllUpdatablePropertiesEquals(Battle expected, Battle actual) {
		assertBattleUpdatableFieldsEquals(expected, actual);
		assertBattleUpdatableRelationshipsEquals(expected, actual);
	}

	/**
	 * Asserts that the entity has all the auto generated properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertBattleAutoGeneratedPropertiesEquals(Battle expected, Battle actual) {
		assertThat(actual)
			.as("Verify Battle auto generated properties")
			.satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
	}

	/**
	 * Asserts that the entity has all the updatable fields set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertBattleUpdatableFieldsEquals(Battle expected, Battle actual) {
		assertThat(actual)
			.as("Verify Battle relevant properties")
			.satisfies(a -> assertThat(a.getModel1Answer()).as("check model1Answer").isEqualTo(expected.getModel1Answer()))
			.satisfies(a -> assertThat(a.getModel2Answer()).as("check model2Answer").isEqualTo(expected.getModel2Answer()))
			.satisfies(a -> assertThat(a.getVoteTimestamp()).as("check voteTimestamp").isEqualTo(expected.getVoteTimestamp()));
	}

	/**
	 * Asserts that the entity has all the updatable relationships set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertBattleUpdatableRelationshipsEquals(Battle expected, Battle actual) {
		assertThat(actual)
			.as("Verify Battle relationships")
			.satisfies(a -> assertThat(a.getPrompt()).as("check prompt").isEqualTo(expected.getPrompt()))
			.satisfies(a -> assertThat(a.getModel1()).as("check model1").isEqualTo(expected.getModel1()))
			.satisfies(a -> assertThat(a.getModel2()).as("check model2").isEqualTo(expected.getModel2()))
			.satisfies(a -> assertThat(a.getWinnerModel()).as("check winnerModel").isEqualTo(expected.getWinnerModel()));
	}
}
