package uibk.llmape.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LeaderboardEntryAsserts {

	/**
	 * Asserts that the entity has all properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertLeaderboardEntryAllPropertiesEquals(LeaderboardEntry expected, LeaderboardEntry actual) {
		assertLeaderboardEntryAutoGeneratedPropertiesEquals(expected, actual);
		assertLeaderboardEntryAllUpdatablePropertiesEquals(expected, actual);
	}

	/**
	 * Asserts that the entity has all updatable properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertLeaderboardEntryAllUpdatablePropertiesEquals(LeaderboardEntry expected, LeaderboardEntry actual) {
		assertLeaderboardEntryUpdatableFieldsEquals(expected, actual);
		assertLeaderboardEntryUpdatableRelationshipsEquals(expected, actual);
	}

	/**
	 * Asserts that the entity has all the auto generated properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertLeaderboardEntryAutoGeneratedPropertiesEquals(LeaderboardEntry expected, LeaderboardEntry actual) {
		assertThat(actual)
			.as("Verify LeaderboardEntry auto generated properties")
			.satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
	}

	/**
	 * Asserts that the entity has all the updatable fields set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertLeaderboardEntryUpdatableFieldsEquals(LeaderboardEntry expected, LeaderboardEntry actual) {
		assertThat(actual)
			.as("Verify LeaderboardEntry relevant properties")
			.satisfies(a -> assertThat(a.getEntryJson()).as("check entryJson").isEqualTo(expected.getEntryJson()))
			.satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
			.satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
	}

	/**
	 * Asserts that the entity has all the updatable relationships set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertLeaderboardEntryUpdatableRelationshipsEquals(LeaderboardEntry expected, LeaderboardEntry actual) {
		// empty method
	}
}
