package uibk.llmape.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModelAsserts {

	/**
	 * Asserts that the entity has all properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertModelAllPropertiesEquals(Model expected, Model actual) {
		assertModelAutoGeneratedPropertiesEquals(expected, actual);
		assertModelAllUpdatablePropertiesEquals(expected, actual);
	}

	/**
	 * Asserts that the entity has all updatable properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertModelAllUpdatablePropertiesEquals(Model expected, Model actual) {
		assertModelUpdatableFieldsEquals(expected, actual);
		assertModelUpdatableRelationshipsEquals(expected, actual);
	}

	/**
	 * Asserts that the entity has all the auto generated properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertModelAutoGeneratedPropertiesEquals(Model expected, Model actual) {
		assertThat(actual)
			.as("Verify Model auto generated properties")
			.satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
	}

	/**
	 * Asserts that the entity has all the updatable fields set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertModelUpdatableFieldsEquals(Model expected, Model actual) {
		assertThat(actual)
			.as("Verify Model relevant properties")
			.satisfies(a -> assertThat(a.getModelName()).as("check modelName").isEqualTo(expected.getModelName()))
			.satisfies(a -> assertThat(a.getOrganization()).as("check organization").isEqualTo(expected.getOrganization()))
			.satisfies(a -> assertThat(a.getProvider()).as("check provider").isEqualTo(expected.getProvider()))
			.satisfies(a -> assertThat(a.getApiKey()).as("check apiKey").isEqualTo(expected.getApiKey()))
			.satisfies(a -> assertThat(a.getBaseUrl()).as("check baseUrl").isEqualTo(expected.getBaseUrl()))
			.satisfies(a -> assertThat(a.getLicense()).as("check license").isEqualTo(expected.getLicense()))
			.satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
	}

	/**
	 * Asserts that the entity has all the updatable relationships set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertModelUpdatableRelationshipsEquals(Model expected, Model actual) {
		// empty method
	}
}
