package uibk.llmape.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PromptAsserts {

	/**
	 * Asserts that the entity has all properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertPromptAllPropertiesEquals(Prompt expected, Prompt actual) {
		assertPromptAutoGeneratedPropertiesEquals(expected, actual);
		assertPromptAllUpdatablePropertiesEquals(expected, actual);
	}

	/**
	 * Asserts that the entity has all updatable properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertPromptAllUpdatablePropertiesEquals(Prompt expected, Prompt actual) {
		assertPromptUpdatableFieldsEquals(expected, actual);
		assertPromptUpdatableRelationshipsEquals(expected, actual);
	}

	/**
	 * Asserts that the entity has all the auto generated properties (fields/relationships) set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertPromptAutoGeneratedPropertiesEquals(Prompt expected, Prompt actual) {
		assertThat(actual)
			.as("Verify Prompt auto generated properties")
			.satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
	}

	/**
	 * Asserts that the entity has all the updatable fields set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertPromptUpdatableFieldsEquals(Prompt expected, Prompt actual) {
		assertThat(actual)
			.as("Verify Prompt relevant properties")
			.satisfies(a -> assertThat(a.getPromptText()).as("check promptText").isEqualTo(expected.getPromptText()))
			.satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
			.satisfies(a -> assertThat(a.getIsRejected()).as("check isRejected").isEqualTo(expected.getIsRejected()))
			.satisfies(a -> assertThat(a.getIsFromPublicPage()).as("check isFromPublicPage").isEqualTo(expected.getIsFromPublicPage()))
			.satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()))
			.satisfies(a -> assertThat(a.getSessionId()).as("check sessionId").isEqualTo(expected.getSessionId()))
			.satisfies(a -> assertThat(a.getGenerationModelId()).as("check generationModelId").isEqualTo(expected.getGenerationModelId()));
	}

	/**
	 * Asserts that the entity has all the updatable relationships set.
	 *
	 * @param expected the expected entity
	 * @param actual the actual entity
	 */
	public static void assertPromptUpdatableRelationshipsEquals(Prompt expected, Prompt actual) {
		// empty method
	}
}
